spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: mySuperSecretKey1234567890_mySuperSecretKey1234567890
  expiration: 3600000